### ISSUE TITLE
ONET VIDEO -> Kodi 19.3

### ISSUE THREAD

**Issue by Tusekowski** [mtr81/kodi_addons#1]
Nie odtwarza materiałów.

Fragment z logów: 

```
2023-02-05 10:31:19.506 T:10128    INFO <general>: initializing python engine.
2023-02-05 10:31:21.472 T:8560     INFO <general>: CPythonInvoker(7, C:\Users\sixki\AppData\Roaming\Kodi\addons\service.xbmc.versioncheck\resources\lib\runner.py): script successfully run
2023-02-05 10:31:21.584 T:8560     INFO <general>: Python interpreter stopped
2023-02-05 10:31:21.585 T:10128   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'inputstreamhelper'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\sixki\AppData\Roaming\Kodi\addons\plugin.video.onet\addon.py", line 202, in <module>
                                                       playVid(link)
                                                     File "C:\Users\sixki\AppData\Roaming\Kodi\addons\plugin.video.onet\addon.py", line 162, in playVid
                                                       import inputstreamhelper
                                                   ModuleNotFoundError: No module named 'inputstreamhelper'
                                                   -->End of Python script error report<--
                                                   
2023-02-05 10:31:21.687 T:10128    INFO <general>: Python interpreter stopped
2023-02-05 10:31:21.707 T:8696    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.onet/?mode=playVid&link=https%3A%2F%2Fwww.onet.pl%2Fvideo%2Fprogramy%2Fkulisy-glosnego-sledztwa-onetu-z-kazdym-momentem-odkrywalismy-kolejne-warstwy-klamstw%2Fws1ht9t%2C6c2ea0e6]
```

**Comment by mtr81** [comment]
Dzieki za info. Poszła do repo poprawiona wersja (1.0.2)

**Comment by Tusekowski** [comment]
Dzięki. Super wtyczka :)
