### ISSUE TITLE
Błąd VOD.pl na Android TV

### ISSUE THREAD

**Issue by hevet** [mtr81/kodi_addons#15]
Od kilku dni przy próbie włączenia dowolnego serialu czy programu włącza się tylko dźwięk, obraz się nie pojawia. Canal+box z Android TV. Poniżej log

2024-02-05 16:14:16.024 T:26461   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 971, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/json/__init__.py", line 346, in loads
                                                       return _default_decoder.decode(s)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vod_pl/addon.py", line 1138, in <module>
                                                       playVid(eid,tid,False,False,None)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vod_pl/addon.py", line 514, in playVid
                                                       resp=requests.get(u,headers=hea_).json()
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 975, in json
                                                       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
                                                   requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2024-02-05 16:14:16.211 T:26178   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vod_pl/?mode=playVid&eid=7316960&tid=seriale_online_1_wielkie_klamstewka_odcinki_7308434]
2024-02-05 16:14:19.253 T:26498 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-02-05 16:14:25.530 T:26178    info <general>: Skipped 52 duplicate messages..
2024-02-05 16:14:25.530 T:26178    info <general>: VideoPlayer::OpenFile: plugin://plugin.video.vod_pl/?mode=playVid&eid=7298830&tid=seriale_online_1_przeklete_miasto_odcinki_7298828
2024-02-05 16:14:25.532 T:26517    info <general>: Creating InputStream
2024-02-05 16:14:25.568 T:26517    info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2024-02-05 16:14:25.569 T:26517   error <general>: GetDirectory - Error getting /data/user/0/org.xbmc.kodi/cache/apk/assets/addons/inputstream.adaptive/
2024-02-05 16:14:26.296 T:26517    info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 2, Type: VOD)
2024-02-05 16:14:26.627 T:26517 warning <general>: AddOnLog: inputstream.adaptive: SaveServiceCertificate: Empty Service Certificate
2024-02-05 16:14:26.816 T:26517    info <general>: Creating Demuxer
2024-02-05 16:14:26.820 T:26517    info <general>: Opening stream: 1002 source: 256
2024-02-05 16:14:26.839 T:26517    info <general>: Creating video codec with codec id: 27
2024-02-05 16:14:26.860 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open: Secure decoder requested: true (stream flags: 1)
2024-02-05 16:14:26.860 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.aac.decoder
2024-02-05 16:14:26.863 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.amrnb.decoder
2024-02-05 16:14:26.864 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.amrwb.decoder
2024-02-05 16:14:26.864 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.flac.decoder
2024-02-05 16:14:26.865 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.g711.alaw.decoder
2024-02-05 16:14:26.865 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.g711.mlaw.decoder
2024-02-05 16:14:26.865 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.mp3.decoder
2024-02-05 16:14:26.866 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.opus.decoder
2024-02-05 16:14:26.867 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.raw.decoder
2024-02-05 16:14:26.867 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.vorbis.decoder
2024-02-05 16:14:26.868 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.vp9.decoder.awesome2
2024-02-05 16:14:26.868 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.audio.decoder.ac3
2024-02-05 16:14:26.868 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.audio.decoder.dtshd
2024-02-05 16:14:26.869 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.audio.decoder.eac3
2024-02-05 16:14:26.869 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.audio.decoder.ffmpeg
2024-02-05 16:14:26.870 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.vp6a.decoder.sw
2024-02-05 16:14:26.872 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.vp6f.decoder.sw
2024-02-05 16:14:26.873 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.avc.decoder.awesome2
2024-02-05 16:14:27.149 T:26517    info <general>: CDVDVideoCodecAndroidMediaCodec:: Open Android MediaCodec OMX.amlogic.avc.decoder.awesome2.secure
2024-02-05 16:14:27.152 T:26517    info <general>: Creating video thread
2024-02-05 16:14:27.153 T:26538    info <general>: running thread: video_thread
2024-02-05 16:14:27.163 T:26517    info <general>: Opening stream: 1001 source: 256
2024-02-05 16:14:27.184 T:26517    info <general>: Finding audio codec for: 86018
2024-02-05 16:14:27.418 T:26517    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2024-02-05 16:14:27.418 T:26517    info <general>: CDVDAudioCodecAndroidMediaCodec Use raw decoder and decode using ff-aac
2024-02-05 16:14:27.430 T:26517    info <general>: CDVDAudioCodecAndroidMediaCodec Open Android MediaCodec amc-aac
2024-02-05 16:14:27.430 T:26517    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2024-02-05 16:14:27.431 T:26517    info <general>: Creating audio thread
2024-02-05 16:14:27.431 T:26546    info <general>: running thread: CVideoPlayerAudio::Process()
2024-02-05 16:14:27.673 T:26546    info <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2024-02-05 16:14:27.766 T:26326    info <general>: CActiveAESink::OpenSink - initialize sink
2024-02-05 16:14:27.777 T:26326    info <general>: Trying to open: samplerate: 48000, channelMask: 12, encoding: 4
2024-02-05 16:14:27.786 T:26326    info <general>: Minimum size we need for stream: 32800 Bytes
2024-02-05 16:14:27.786 T:26326    info <general>: Audiotrack buffer params are: period time = 42.708 ms, period size = 16400 bytes, num periods = 4
2024-02-05 16:14:27.786 T:26326    info <general>: Created Audiotrackbuffer with playing time of 170.833333 ms min buffer size: 65600 bytes
2024-02-05 16:14:27.835 T:26326    info <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 48000 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 65600 m_frames: 2050 m_frameSize: 8 channels: 2
2024-02-05 16:14:31.011 T:26178    info <general>: Loading skin file: VideoFullScreen.xml, load type: KEEP_IN_MEMORY
2024-02-05 16:14:52.316 T:26178    info <general>: CVideoPlayer::CloseFile()
2024-02-05 16:14:52.318 T:26178    info <general>: VideoPlayer: waiting for threads to exit
2024-02-05 16:14:52.320 T:26517    info <general>: CVideoPlayer::OnExit()
2024-02-05 16:14:52.321 T:26517    info <general>: Closing stream player 1
2024-02-05 16:14:52.322 T:26517    info <general>: Waiting for audio thread to exit
2024-02-05 16:14:52.343 T:26546    info <general>: thread end: CVideoPlayerAudio::OnExit()
2024-02-05 16:14:52.343 T:26517    info <general>: Closing audio device
2024-02-05 16:14:52.365 T:26326    info <general>: CActiveAESink::OpenSink - initialize sink
2024-02-05 16:14:52.366 T:26517    info <general>: Deleting audio codec
2024-02-05 16:14:52.374 T:26326    info <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2024-02-05 16:14:52.377 T:26326    info <general>: Minimum size we need for stream: 30160 Bytes
2024-02-05 16:14:52.377 T:26326    info <general>: Audiotrack buffer params are: period time = 42.744 ms, period size = 15080 bytes, num periods = 4
2024-02-05 16:14:52.377 T:26326    info <general>: Created Audiotrackbuffer with playing time of 170.975057 ms min buffer size: 60320 bytes
2024-02-05 16:14:52.393 T:26326    info <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 60320 m_frames: 1885 m_frameSize: 8 channels: 2
2024-02-05 16:14:52.395 T:26517    info <general>: Closing stream player 2
2024-02-05 16:14:52.396 T:26517    info <general>: waiting for video thread to exit
2024-02-05 16:14:52.396 T:26538    info <general>: thread end: video_thread
2024-02-05 16:14:52.398 T:26517    info <general>: deleting video codec
2024-02-05 16:14:52.499 T:26356    info <general>: Deleting settings information for files plugin://plugin.video.vod_pl/?mode=playVid&eid=7298830&tid=seriale_online_1_przeklete_miasto_odcinki_7298828
2024-02-05 16:14:52.503 T:26517    info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2024-02-05 16:14:52.505 T:26178    info <general>: VideoPlayer: finished waiting
2024-02-05 16:14:52.505 T:26178    info <general>: CVideoPlayer::CloseFile()
2024-02-05 16:14:52.505 T:26178    info <general>: VideoPlayer: waiting for threads to exit
2024-02-05 16:14:52.505 T:26178    info <general>: VideoPlayer: finished waiting
2024-02-05 16:14:52.576 T:26178   error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-02-05 16:14:53.352 T:26498 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.

**Comment by mtr81** [comment]
Problem w aktualizacji ISA 20.3.17. Wczoraj zgłosiłem gdzie trzeba. Podobna sytuacja jest we wtyczce player.pl i kilku innych. Dotyczy to urządzeń z androidem.

**Comment by hevet** [comment]
Ok, dzięki 🙂

**Comment by aprof28** [comment]
Witam. vod.pl przestał istnieć . Dostałem emaila. To samo jest a nawet więcej na Player . https://m.wirtualnemedia.pl/m/artykul/vod-pl-player-tvn-tvn7-ttv-metro-na-zywo-bez-anteny-bezplatnie-jak-ogladac

**Comment by mtr81** [comment]
Formalnie tak, natomiast serwis dalej jest aktywny, tyle że nie dodają nowych rzeczy. Natomiast problem, który zgłosił @hevet jest o wiele szerszy i dotyczy nie tylko tego tej wtyczki, ale i innych (włączając playera) i wywołała go ostatnia aktualizacja inputstream adaptive.

**Comment by aprof28** [comment]
Zrozumiałem. Bez odbioru ;-)

**Comment by mm1992** [comment]
Uuu, to widzę poważny problem. Ja kiedyś miałem praktycznie identyczny problem na Androidzie. Męczyłem się ze dwa lata (!) pisząc issues na różnych repozytoriach aż w końcu to naprawili w Kodi20 i którymś tam InputStream.
Morał taki żeby na razie **nie aktualizować** ISA na Androidzie. Dobrze wiedzieć. ;)

**Comment by mtr81** [comment]
W najnowszych wersjach ISA (20.3.18/21.4.3) problem został rozwiązany.
