### ISSUE TITLE
Wtyczka megogo.

### ISSUE THREAD

**Issue by zuzia-dev** [mtr81/kodi_addons#2]
Nie działa. Wersja wtyczki: v1.0.3, Kodi 20.1, Linux Debian, najnowsza ISA.

```
2023-06-30 16:44:25.089 T:2787105   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/zuzia/.kodi/addons/plugin.video.megogo/addon.py", line 252, in <module>
                                                       tvList('live')
                                                     File "/home/zuzia/.kodi/addons/plugin.video.megogo/addon.py", line 67, in tvList
                                                       chans=channels()
                                                     File "/home/zuzia/.kodi/addons/plugin.video.megogo/addon.py", line 63, in channels
                                                       chans=[c['objects'] for c in cGroups if c['type_name']=='Bezpłatna telewizja' ][0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2023-06-30 16:44:25.244 T:2787423   error <general>: GetDirectory - Error getting plugin://plugin.video.megogo/?mode=live&page=0
2023-06-30 16:44:25.245 T:2612276   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.megogo/?mode=live&page=0) failed
```

**Comment by mtr81** [comment]
Dzięki za info! Poprawka poszła do repo.

**Comment by zuzia-dev** [comment]
W v1.0.4 działa jak należy. Dziękuję za szybką poprawka, bardzo fajna wtyczka.
